tools: make bazel-vscode plugin work in the monorepo
Set Bazel executable and remove stdout pollution.

Change-Id: I2d1d7fb613e7e7a55d34c3e33b7a9e204e866879
Reviewed-on: https://review.monogon.dev/c/monogon/+/4308
Tested-by: Jenkins CI
Reviewed-by: Lorenz Brun <lorenz@monogon.tech>

diff --git a/tools/bazel b/tools/bazel
--- a/tools/bazel
+++ b/tools/bazel
@@ -125,7 +125,7 @@ intellij_patch() {
               echo "IntelliJ found at ${ij_home}, aspect repository already patched." >&2
           fi
       else
-        echo "IntelliJ found at ${ij_home}, but aspect repository is missing. Skipping..."
+        echo "IntelliJ found at ${ij_home}, but aspect repository is missing. Skipping..." >&2
       fi
   fi
 }
